name: Release
on:
    push:
        tags:
            - "v*.*.*"
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set-up Node
              uses: actions/setup-node@v3
              with:
                node-version: '16'
                cache: 'yarn'
                registry-url: 'https://registry.npmjs.org'
            - name: Install deps
              run: yarn install --frozen-lockfile
            - name: Build
              run: yarn build
            - name: Upload release asset
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: ./dist/autoscroll.js
                asset_name: autoscroll.js
                tag: ${{ github.ref }}
                overwrite: true